version: '2'

services:
  minio:
    image: gcavalcante8808/minio-dev:latest
    build: .
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_INITIAL_BUCKET: default
      MINIO_INITIAL_BUCKET_PERMISSION: none

